
services:
  mcp:
    container_name: mcp_test_go
    image: mcr.microsoft.com/vscode/devcontainers/go:dev-1.25-bookworm
    networks:
      - mcp
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./src:/go/src/mcp
  
networks:
  mcp:
    name: mcp
    driver: bridge
